/*
 * Copyright (c) 2023-2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef TEST_SINGLE_PLAYER_SLOW_1_H
#define TEST_SINGLE_PLAYER_SLOW_1_H

#include <chrono>
#include <thread>
#include "testngpp/testngpp.hpp"
#include "helper/test_player.hpp"

using namespace OHOS::Media::Test;

// @fixture(tags=audio_play_slow)
FIXTURE(dataDrivenSinglePlayerTestSlow1)
{
    DATA_PROVIDER(myurls, 1,
    DATA_GROUP(std::string(RESOURCE_DIR "/MP3/MP3_LONG_48000_32.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/M4A/MPEG-4_48000_32_LONG.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/02-400Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/03-500Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/04-600Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/05-700Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/06-800Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/07-900Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/08-1kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/09-2kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/10-3kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/100Hz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1077205091002.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/10KHz-stero.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/11-4kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/12-5kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/12KHz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/13-6kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/14-7kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/15-8kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/150Hz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/15KHz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/16-9kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/17-10kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/18-12kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/180Hz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/19-16kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1KHz-44.1K-sine_-6dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1KHz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1KHz-stero.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/20-20kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/200Hz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/20Hz-stero.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/2kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/AngleAudioEffect-1.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/Chains.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_192k_16bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_192k_24bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_192k_32bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_48k_32bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_96k_16bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_96k_24bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_96k_32bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/chushan-1.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/chushan.wav")),
    // TO FIX: ffmpeg wav demuxer cause crash  RESOURCE_DIR "/../../../../resource_ext/WAV/dash-runner-8bit.wav
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/dash-runner-8bit_short.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/short_music.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/sound_voices-1.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/sound_voices.wav")),

    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AACLC_1channel_001.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/00-200Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/01-300Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/02-400Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/03-500Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/04-600Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/05-700Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/06-800Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/07-900Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/08-1kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/09-2kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/1.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/10-3kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/100Hz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/11-4kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/12-5kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/12KHz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/13-6kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/14-7kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/15-8kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/150Hz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/15KHz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/16-9kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/17-10kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/171005793.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/18-12kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/180Hz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/19-16kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/1KHz-44.1K-sine_-6dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/1KHz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/1kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/20-20kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/200Hz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/2kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AACLC_1channel_001.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AM playing.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AM radio.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Bye_Bye_Bye-Lovestoned-19466604.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Call to 1669.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~1.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~2.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~3.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~4.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~5.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Change frequency 97.5 FM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Change to a route that avoids tolls..aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Change to an economical route.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Change to the nearest route.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Changed to AM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Changed to FM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chinese148755.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Close the window on passenger side.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Close the window on the drive side.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Cover27487643.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Save as a favorite son.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Set play mode loop all---All swirls.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Set play mode shuffle---Play randomly.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Switch to fastest route.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/a2002011001-e02-8kHz.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/add home address.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/add work address.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/ail_ext.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/ail_int.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow face foot.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow face.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow foot.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow_windscreen.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow_windscreen_foot.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/bridgegril85595213.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/call back.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/callcenter.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/cancel.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/close the AC .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/close the roof .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/cool down the temperature .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/dash-runner-8bit.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/dash-runner-8bit_short.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/decrease the fan speed please.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/defrost_off.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/defrost_on.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/j_fa2_hev2.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/m_a_he.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/meet.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/out.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/out~1.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/resume music.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sample_16kHz.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sample_16kHz_2.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sample_32kHz.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sample_441.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/short_music.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/size up.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sounds on please.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/take me back to the previous .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/take me to settings.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/test_48000Hz_32bit_1Channel.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/test_file_acc.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/tune to 837 AM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/turn down the light to the lowest.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/turn on the maximum fan speed.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/want to add this station to favorite .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/warmer on .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/yes.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/zoom out the map.aac")),

    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/002-100Hz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/003-1KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/004-10KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/005-20KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/006-1KHz-L.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/007-1KHz-R.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/008-10KHz-L.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/009-10KHz-R.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/10KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/1KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/20Hz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/20kHz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/456.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/add home address.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/add work address.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/ail_ext.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/ail_int.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/AM playing.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/AM radio.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/AM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/angel_audio.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/attach_picture.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/background.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow face foot.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow face.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow foot.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow_windscreen.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow_windscreen_foot.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/call back.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Call to 1669.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/callcenter.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/cancel.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Catherine.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Chains.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Change frequency 97.5 FM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Change to a route that avoids tolls..mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Change to an economical route.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Change to the nearest route.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Changed to AM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Changed to FM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/clap.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/close the AC .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/close the roof .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Close the window on passenger side.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Close the window on the drive side.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/cool down the temperature .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/dash-runner-8bit_short.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/decrease the fan speed please.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/defrost_off.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/defrost_on.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/dream_it_possible.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/foreverLove.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/resume music.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Set play mode loop all---All swirls.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Set play mode shuffle---Play randomly.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/short_music.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/size up.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/sounds on please.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Switch to fastest route.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/take me back to the previous .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/take me to settings.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/test-2sec.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track02_1kHz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track03_17Hz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track04_127Hz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track05_997Hz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track06_10kHz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track07_20kHz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track08_MUTE.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track09_1kHz_L.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track11_1kHz_R.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/tune to 837 AM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/turn down the light to the lowest.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/turn on the maximum fan speed.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/want to add this station to favorite .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/warmer on .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/xiaoluluanzhuang-1.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/xiaoluluanzhuang.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/yes.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/zoom out the map.mp3")),

    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/00-200Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/01-300Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/02-400Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/03-500Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/04-600Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/05-700Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/06-800Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/07-900Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/08-1kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/09-2kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/10-3kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/100Hz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1077205091002.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/11-4kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/12-5kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/12KHz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/13-6kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/14-7kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/15-8kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/150Hz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/15KHz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/16-9kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/17-10kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/171005793.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/18-12kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/180Hz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/19-16kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1KHz-44.1K-sine_-6dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1KHz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/20-20kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/200Hz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/2kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/a2002011001-e02-8kHz.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/add home address.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/add work address.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/ail_ext.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/ail_int.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/AM playing.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/AM radio.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/AM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow face foot.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow face.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow foot.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow_windscreen.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow_windscreen_foot.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/bridgegril85595213.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Bye_Bye_Bye-Lovestoned-19466604.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/call back.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Call to 1669.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/callcenter.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/cancel.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~1.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~2.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~3.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~4.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~5.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Change frequency 97.5 FM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Change to a route that avoids tolls..ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Change to an economical route.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Change to the nearest route.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Changed to AM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Changed to FM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chinese148755.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/close the AC .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/close the roof .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Close the window on passenger side.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Close the window on the drive side.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/cool down the temperature .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Cover27487643.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/dash-runner-8bit.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/decrease the fan speed please.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/defrost_off.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/defrost_on.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Iamnotinyourmemory.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/meet.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/out.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/out~1.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/resume music.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sample_16kHz.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sample_16kHz_2.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sample_32kHz.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sample_441.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Save as a favorite son.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Set play mode loop all---All swirls.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Set play mode shuffle---Play randomly.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/size up.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sounds on please.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Switch to fastest route.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/take me back to the previous .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/take me to settings.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/test_file_acc.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/tune to 837 AM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/turn down the light to the lowest.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/turn on the maximum fan speed.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/want to add this station to favorite .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/warmer on .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/yes.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/zoom out the map.ape")));

	// @test(data="myurls")
    PTEST((std::string url), Test single player play url music, and finished automatically)
    {
        std::unique_ptr<TestPlayer> player = TestPlayer::Create();
        ASSERT_EQ(0, player->SetSource(TestSource(url)));
        ASSERT_EQ(0, player->Prepare());
        ASSERT_EQ(0, player->Play());
        while (player->IsPlaying()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(1000));
        }
    }
};
#endif